version: '3'
services:
  ssb_server:
    container_name: ssb-server.local
    image: ghcr.io/chronicleprotocol/ssb_server:latest
    ports:
      - "8007:8007"
      - "8988:8988"
    volumes:
      - "~/ssb-config/config:/root/.ssb/config"
      - "~/ssb-config/secret:/root/.ssb/secret"

  omnia:
    depends_on:
      - ssb_server
    image: ghcr.io/chronicleprotocol/omnia:latest
    volumes:
      - "~/omnia-config/omnia.json:/home/omnia/omnia.json"

      - "~/ssb-config/config:/home/omnia/.ssb/config"
      - "~/ssb-config/secret:/home/omnia/.ssb/secret"

    environment:
      SSB_KEYS: "/home/omnia/.ssb/secret"
      SSB_CONF: "/home/omnia/.ssb/config"
      SSB_HOST: "ssb-server.local"
      SSB_PORT: "8007"
      OMNIA_VERBOSE: "true"
#      OMNIA_LOG_FORMAT: "json"

networks:
  default:
    name: omnia_network
